spring.application.name=ToDoList

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=ankit
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update

# Oracle dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect